assets/_collapsible.scss
assets/_custom.scss
config/_default/config.yml
layouts/partials/docs/menu.html
static/js/collapsible.js

Implement collapsibles on sidebar menu

---

layouts/partials/docs/menu.html

Fix Hugo templating issue

---

.github/workflows/payout-calc.yml

Fix typo in payout calculation workflow

---

.gitignore
payout-calc/__main__.py

Payout Calc: Fix diff parsing & improve logging

---

content/attacks/posts/2023-03-13-Euler-Finance.md

Detailed report for Euler Finance exploit with sources

2023-03-13-Euler-Finance

---

content/attacks/posts/2021-12-05-Polygon.md

Main added 2021-12-05-Polygon.md

---

.github/workflows/fact-check-comment.yaml

add wiki reviewers secret

---

content/attacks/posts/2013-05-23-Feathercoin.md
content/attacks/posts/2016-08-23-Krypton.md
content/attacks/posts/2016-08-27-Shift.md
content/attacks/posts/2018-01-28-Coincheck.md
content/attacks/posts/2018-04-04-Verge.md
content/attacks/posts/2018-05-19-Bitcoin-Gold.md
content/attacks/posts/2018-10-24-Vertcoin.md
content/attacks/posts/2018-11-AurumCoin-Cryptopia.md
content/attacks/posts/2019-01-05-Ethereum-Classic.md
content/attacks/posts/2019-05-15-Bitcoin-Cash.md
content/attacks/posts/2020-01-23-Bitcoin-Gold.md
content/attacks/posts/2020-08-29-Ethereum-Classic.md
content/attacks/posts/2021-08-10-poly-network.md
content/attacks/posts/2021-12-05-Polygon.md
content/attacks/posts/2021-12-13-Vulcan-Forged.md
content/attacks/posts/2022-02-02-Wormhole.md
content/attacks/posts/2022-03-23-Ronin.md
content/attacks/posts/2022-04-17-Beanstalk.md
content/attacks/posts/2022-05-08-Terra-Classic.md
content/attacks/posts/2022-06-23-Harmony-Horizon.md
content/attacks/posts/2022-09-20-Wintermute.md
content/attacks/posts/2022-10-06-BSC-Token-Hub.md
content/attacks/posts/2023-03-13-Euler-Finance.md
content/attacks/posts/2023-05-29-Qubit.md

https://github.com/1712n/dn-institute/pull/117#issuecomment-1606261855
I checked the headers and left `custodians` headers only in articles with the `category` "custodians".
Changed some categories, cause often they seem pretty random, somebody with better understanding should approve my changes. Probably more clarification on what a category for an attack is needed for contributors as they often confuse it with something like tags
I think we should create other headers to allow taxonomy based on different attributes, i.e entity affected (including networks and defi platforms) - to be discussed @evgenydmitriev. More clarification on what custodian means and when this header is needed to be added to readme

headers-edits

---

content/attacks/posts/2020-09-25-KuCoin.md

1. KuCoin article in KuCoin branch. One article - one branch.
2. Removed excessive links.
3. Removed duplicated sentence.
4. Added quotes to the title.

KuCoin - fixed

---

content/attacks/posts/2022-04-17-Beanstalk.md

1. Updated the article in accordance with new plagiarism checker (https://github.com/1712n/dn-institute/pull/140).
2. Made separate pull request for the article (before there were two articles - Beanstalk and Wormhole - in one branch and one PR).
P.S. This article was already published and I was already paid for it. That is, it's just to eliminate plagiarism and mistakes in the text.

Beanstalk update - fixed plagiarism and writing issues

---

content/attacks/posts/2022-02-02-Wormhole.md

1. Updated the article in accordance with new plagiarism checker (2019-11-27-Upbit Article #140).
2. Made separate pull request for the article (before there were two articles - Beanstalk and Wormhole - in one branch and one PR).
P.S. This article was already published and I was already paid for it. That is, it's just to eliminate plagiarism and mistakes in the text.

Wormhole update - fixed plagiarism and writing issues

---

.github/workflows/payout-calc.yml

@JediFaust this should allow you to approve payouts

move wiki reviewers to secrets

---

README.md

making headers more generic and broad, to allow categorization based on entity name, type or type of attack. After approval I will fix headers in existing posts. @danisztls please check that it will not ruin current taxonomy

Change headers

---

assets/_custom.scss
content/attacks/posts/categories/_index.md
content/attacks/posts/custodians/_index.md
layouts/partials/docs/post-meta.html
layouts/taxonomy/terms.html

@marina-chibizova Just fixing small issues. This isn't related to #169.

Taxonomies: Small fixes

---

content/attacks/posts/2017-07-18-Parity.md

Earlier hack of Parity MultiSig Wallet

2017-07-18-Parity

---

README.md

added new header names. @jhirschkorn, @eric-oconnor fyi

headers-names

---

README.md

Provided full list of current `Entity Types` and `Attack Types`.

Updated list of attack and entity types

---

content/attacks/posts/2022-03-23-Ronin.md

- Added Lazarus Group involvement with the source
- Fixed and extended headers

Lazarus Update for the Ronin incident

---

tools/payout_calc.py

Tools: Fix payout script

---

content/attacks/docs/flashloan.md

Article with Flash Loan Attacks explanation and referenced examples from the Crypto Attacks Wiki

Flash Loan Attack Article

---

content/attacks/posts/2019-02-20-Coinbin.md

Coinbin Embezzlement and Youbit, Yapizon combined hack article

2019-02-20-Coinbin

---

tools/grammar_checker.py

- Fixed context dropping initial letters
- Fix empty replacements

Grammar Checker Fixes

---

tools/grammar_checker.py

- Fixed issue where replacements not showing

Replacements fix for Grammar Checker

---

tools/grammar_checker.py

Fixed Custom Dictionary for Spell Checker not triggered

Dictionary Fixes

---

layouts/partials/docs/menu-filetree.html

Honor param bookCollapseSection

---

content/attacks/posts/2023-09-04-Stake.md

Stake.com incident Lazarus Group involved

Lazarus Involved Stake.com Article

---

content/attacks/posts/2023-09-23-Mixin-Network.md

Hello. My name is Alexander Evdokimov. I have created a wiki post for a mixin network hack at 2023-09-23 as a condition for applying for an Investigation analyst. https://geekjob.ru/vacancy/65129c9538bb26b34f002489

Created a wiki post for a mixin network hack at 2023-09-23

---

content/attacks/posts/2019-06-02-Kraken.md

Kraken Flash Crash of Bitcoin-Canadian Dollar pair

Kraken Flash Crash Article

---

.github/workflows/article-check.yml
pyproject.toml
tools/article_checker.py
tools/config.json
tools/config.py

Bot uses WebPilot API for fact-checking (LLM+web search). Works faster, provides links to the sources used for fact-checking. Need WebPilot key

Add LLM-based fact-checker

---

.github/workflows/article-check-claude.yml
.github/workflows/duplication-check.yml
poetry.lock
pyproject.toml
tools/README.md
tools/article_checker_claude.py
tools/claude_retriever/__init__.py
tools/claude_retriever/client.py
tools/claude_retriever/searcher/searchtools/websearch.py
tools/claude_retriever/searcher/types.py
tools/claude_retriever/utils.py
tools/config.json
tools/duplication_checker.py
tools/llm_utils.py

- Now the bot that checks new articles from PRs uses Claude. Additional logic for the retriever has been added. The prompt has been expanded: it performs fact-checking, spell-checking, and checks the file name, as well as compliance with the submission guidelines
- A bot has been added that checks whether an article from a PR is new to Crypto Wiki. It takes a list of existing articles by target entity and checks for similarities between the new text and the old ones using GPT-3.
- README.md updated
[Example 1](https://github.com/Kseymur/dn-institute/pull/31)
[Example 2](https://github.com/Kseymur/dn-institute/pull/32)

New GitHub bots

---

tools/article_checker_claude.py
tools/claude_retriever/client.py
tools/claude_retriever/searcher/searchtools/websearch.py

I have modified the retriever so that it searches for each statement separately. Unfortunately, it became clear that Claude is not very effective at spell checking. The model can rewrite the text, correcting errors, but does not produce a list of errors as required. I am trying to solve this task by trying different prompts. Perhaps it makes sense to use a separate grammar checker (gpt-4) until I solve the problem. P.S. The suggested PPLX models struggle with long multi-task prompts.
[Example](https://github.com/Kseymur/dn-institute/pull/33)

fix retriever

---

tools/article_checker_claude.py
tools/claude_retriever/client.py

1. Fixed the comment generation function so it can post a comment in a pull request without en error even if the LLM doesn't provide all sections.
2. Added to the prompt a request for an explanation as to why the Hugo checking returns False

Improving checker bot

---

tools/article_checker_claude.py
tools/claude_retriever/client.py

1. Removed the complex function for generating pull request comments and delegated this task to LLM.
2. Added a warning symbol for outputs where LLM is uncertain.
3. Slightly refactored prompts and code.

improve prompts and structure of the article checker bot

---

content/attacks/posts/2023-11-10-Poloniex.md

Rewrited the recent Poloniex article from scratch, since it lacked most important information and contained style and formatting issues:
- Added suspects about Lazarus Group being involved
- Added relevant headers
- Added on-chain data as attackers address, initial malicious transaction and bounty offer
- Extended timeline with key events

Poloniex Article Rewrite

---

content/attacks/posts/2023-09-24-HTX.md

HTX white hat incident article with on-chain proofs

HTX White Hat Hack

---

content/attacks/posts/2023-09-24-HTX.md

Fixed issue with Non Breaking Space character, that was generated by my text editor and was breaking Hugo deployment.

NBSP formatting fixes

---

tools/payout_calc.py

feat: add fixed payout

---

content/attacks/posts/2023-11-22-KyberSwap.md

Fixed filename, wrong links and headers.

KyberSwap article fixes

---

content/attacks/docs/lockout.md

Lockout Scam type article with malicious code examples

Lockout Attack Type

---

tools/claude_retriever/utils.py
tools/config.json

anthropic [doesn't support](https://github.com/1712n/dn-institute/actions/runs/8621609543/job/23630881240#step:5:70) gen 3 models in the old endpoint

Anthropic model fix

---

poetry.lock
pyproject.toml
tools/article_checker/article_checker_claude.py
tools/article_checker/claude_retriever/utils.py
tools/article_checker/duplication_checker.py

@Kseymur could you also [add bleach](https://github.com/1712n/dn-institute/actions/runs/8950071209/job/24585044550#step:5:27)?

fix dependencies

---

tools/README.md

@Kseymur, please review this pull request as part of the repository maintenance challenge.
Refactored the README.md file to improve readability and ensure it's up-to-date with the current state of the tools. The target audience is newcomers with minimal tech skills, so the focus was on simplicity and ease of understanding. Used Markdown and GitHub's advanced formatting to make it visually appealing.
- **Simplicity:** Ensured all instructions are clear and easy to follow for users with minimal tech skills.
- **Formatting:** Used headings, lists, and code blocks to organize content logically.
- **Visual Appeal:** Added emojis and proper spacing to make the document engaging and easy to read.
- **Current Information:** Verified and updated all tool descriptions to reflect their current …

Refactored README for better readability and updated content

---

tools/README.md

Updated ReadMe for better readability

Updated README.md

---

content/research/ai/synthetic-data.md

this pr adds **resources** section (arxiv paper & gsheets add-on) and links to the deduplication service

feat: adding resources & urls
